model:
  model_name: ./models_manual/slo-gpt-j-6b
  IN_LEN: 40
  OUT_LEN: 60

train:
  SEED: 42
  TRAIN_BATCH_SIZE: 64
  VALID_BATCH_SIZE: 64
  TRAIN_EPOCHS: 3
  VALID_EPOCHS: 1
  LEARNING_RATE: 0.00001

test:
  TEST_TOP_K: 40
