model:
  model_name: macedonizer/sl-gpt2
  IN_LEN: 20
  OUT_LEN: 50

train:
  SEED: 42
  TRAIN_BATCH_SIZE: 64
  VALID_BATCH_SIZE: 64
  TRAIN_EPOCHS: 3
  VALID_EPOCHS: 1
  LEARNING_RATE: 0.00005

test:
  TEST_BATCH_SIZE: 64
  TEST_TOP_K: 40
